# Generated by Django 4.0.3 on 2023-09-20 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEvent', '0002_fournisseurs_event_image_facture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
